version: "3.7"
services:
  openehr:
    image: "ehrbase/ehrbase:next"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
    depends_on:
      - db
    ports:
      - 5002:8080
  fhir:
    image: "tornadoalert/fhir:v5.4.1-nats"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/hapi"
      spring.datasource.username: hapi
      spring.datasource.password: hapi
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY
      hapi.fhir.nats: "nats://nats:4222"
    depends_on: 
      - db
    ports:
      - 5001:8080
  db:
    image: postgres:13.4
    command: 
      - -c
      - max_replication_slots=10
      - -c
      - wal_level=logical
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  
  caddy:
    image: caddy:2.4.1
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


  kratos-migrate:
    image: oryd/kratos:latest-sqlite
    environment:
      - DSN=postgres://kratos:kratos@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
 

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest-sqlite
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:kratos@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://localhost/kratos/public
      - SERVE_ADMIN_BASE_URL=http://kratos:4434/
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://localhost/auth
      - SELFSERVICE_WHITELISTED_RETURN_URLS=http://localhost/auth/,https://google.com
      - SELFSERVICE_FLOWS_ERROR_UI_URL=http://localhost/auth/error
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=http://localhost/auth/settings
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=http://localhost/auth/recovery
      - SELFSERVICE_FLOWS_VERIFICATION_UI_URL=http://localhost/auth/verify
      - SELFSERVICE_FLOWS_VERIFICATION_AFTER_DEFAULT_BROWSER_RETURN_URL=http://localhost/auth
      - SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL=http://localhost/auth/login
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=http://localhost/auth/login
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://localhost/auth/registration
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos


  hydra:
    image: oryd/hydra:v1.10.6
    command:
      serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      -
        type: bind
        source: ./hydra
        target: /etc/config/hydra
    environment:
      - DSN=postgres://hydra:hydra@db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - URLS_SELF_ISSUER=http://localhost/hydra/public
      - URLS_CONSENT=http://localhost/auth/hydraconsent
      - URLS_LOGIN=http://localhost/auth/hydralogin
      - URLS_LOGOUT=http://localhost/auth/hydralogout
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE,OPTIONS
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE,OPTIONS
      - URLS_POST_LOGOUT_REDIRECT=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - hydra-migrate
   

  hydra-migrate:
    image: oryd/hydra:v1.10.6
    environment:
      - DSN=postgres://hydra:hydra@db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      -
        type: bind
        source: ./hydra
        target: /etc/config/hydra
    restart: on-failure
   

  auth:
    image: athulknair123/auth-flow:v0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_BROWSER_URL=http://localhost/kratos/admin
      - BASE_URL=http://localhost/auth
      - HYDRA_ADMIN_URL=http://hydra:4445
      - LOGO_URL=https://www.kadencewp.com/wp-content/uploads/2020/10/alogo-2.svg
      - PORT=4455

  registry:
    image: medblocks/admin:v1
    ports:
      - "5000:8080"
    environment:
      HYDRA_URL: http://localhost/hydra/admin


volumes: 
  db-data:
  caddy_data:
  caddy_config:


 
 
